version: "3.8"
services:
  back:
    image: tlc_back:latest
    hostname: api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    hostname: db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  etherpad:
    image: etherpad/etherpad:latest
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  
  front:
    image: tlc_front:latest
    hostname: front
    ports:
      - "4200:80"
    depends_on:
      - back
    restart: always